name: PrestaToSap
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: prestatosap-mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=UHJlc3RhVG9TYXAh
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
volumes:
  mssqldata:
